[project]
name = "acp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "acp-sdk>=0.12.1",
    "crewai>=0.130.0",
    "crewai-tools>=0.47.1",
    "ollama>=0.5.1",
    "smolagents>=1.18.0",
]
